[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.gunicorn"]

[phases.install]
cmds = [
  "python -m venv /app/venv",
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "/app/venv/bin/python manage.py collectstatic --noinput",
  "/app/venv/bin/python manage.py migrate --noinput"
]

[start]
cmd = "/app/venv/bin/gunicorn puddle.wsgi:application --bind 0.0.0.0:8000"
# cmd = "/app/venv/bin/python manage.py runserver 0.0.0.0:8000"